plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinJvm) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.kover)
}

dependencies {
    kover(projects.shared)
    kover(projects.composeApp)
}

kover {
    reports {
        filters {
            excludes {
                classes(
                    "*Fragment",
                    "*Fragment\$*",
                    "*Activity", 
                    "*Activity\$*",
                    "*.databinding.*",
                    "*.BuildConfig",
                    "*\$WhenMappings",
                    "*ComposableSingletons*",
                    "*_Impl",
                    "*_Impl\$*"
                )
                packages(
                    "*.build.*"
                )
            }
        }
        total {
            html {
                onCheck = false
                title = "CollabStream Test Coverage Report"
            }
            xml {
                onCheck = false
            }
        }
    }
}

tasks.register("generateCoverageComment") {
    dependsOn("koverHtmlReport")
    
    doLast {
        val reportDir = file("build/reports/kover")
        val htmlReport = file("$reportDir/html/index.html")
        val outputFile = file("build/coverage-comment.md")
        
        if (!htmlReport.exists()) {
            println("No coverage report found at ${htmlReport.path}")
            return@doLast
        }
        
        val htmlContent = htmlReport.readText()
        val coverageComment = parseCoverageFromHtml(htmlContent)
        
        outputFile.writeText(coverageComment)
        println("Coverage comment generated at ${outputFile.path}")
    }
}

fun parseCoverageFromHtml(htmlContent: String): String {
    // Extract overall coverage from the first table (all classes row)
    val overallRegex = """<td class="name">all classes</td>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?<td class="coverageStat"\s*/>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>""".toRegex(RegexOption.DOT_MATCHES_ALL)
    val overallMatch = overallRegex.find(htmlContent)
    
    if (overallMatch == null) {
        return "## 📊 Test Coverage Report\n\nNo coverage data available."
    }
    
    val classPercent = overallMatch.groupValues[1]
    val methodPercent = overallMatch.groupValues[2]
    val linePercent = overallMatch.groupValues[3]
    val instructionPercent = overallMatch.groupValues[4]
    
    // Extract package-level coverage from the breakdown table
    val packageRegex = """<tr>\s*<td[^>]*><a[^>]*>([^<]+)</a></td>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?(?:<td class="coverageStat"\s*/>|<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>).*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>.*?<span class="percent">\s*(\d+(?:\.\d+)?%)\s*</span>""".toRegex(RegexOption.DOT_MATCHES_ALL)
    val packageMatches = packageRegex.findAll(htmlContent).toList()
    
    val comment = StringBuilder()
    comment.append("## 📊 Test Coverage Report\n\n")
    
    comment.append("### Overall Coverage\n")
    comment.append("| Metric | Coverage |\n")
    comment.append("|--------|----------|\n")
    comment.append("| **Classes** | **${classPercent}** |\n")
    comment.append("| **Methods** | **${methodPercent}** |\n")
    comment.append("| **Lines** | **${linePercent}** |\n")
    comment.append("| **Instructions** | **${instructionPercent}** |\n\n")
    
    if (packageMatches.isNotEmpty()) {
        comment.append("<details>\n<summary>📋 Package Coverage Details</summary>\n\n")
        comment.append("| Package | Classes | Methods | Branches | Lines | Instructions |\n")
        comment.append("|---------|---------|---------|----------|-------|-------------|\n")
        
        packageMatches.forEach { match ->
            val packageName = match.groupValues[1]
            val classes = match.groupValues[2]
            val methods = match.groupValues[3]
            val branches = if (match.groupValues[4].isNotEmpty()) match.groupValues[4] else "N/A"
            val lines = match.groupValues[5]
            val instructions = match.groupValues[6]
            
            comment.append("| ${packageName} | ${classes} | ${methods} | ${branches} | ${lines} | ${instructions} |\n")
        }
        
        comment.append("\n</details>\n")
    }
    
    comment.append("\n> Generated by Kover")
    
    return comment.toString()
}

